{
 "title": "OPNSense",
 "description": "OPNSense metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_cpu_temperature_celsius{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",cpu=\"0\"}",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"} - node_boot_time_seconds{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",mode=\"idle\"}[1m])) * 100 / scalar(count(node_cpu_seconds_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",mode=\"user\"}))"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_free_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"} + node_memory_inactive_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Free Swap",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_swap_size_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"} - node_memory_swap_used_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}"
    }
   ]
  },
  {
   "title": "Free Storage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",fstype=\"ufs\"})"
    }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_exec_forks_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Forks"
    },
    {
     "expr": "node_exec_system_calls_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "System Calls"
    },
    {
     "expr": "node_exec_traps_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Traps"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": " irate(node_exec_device_interrupts_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}[5m])",
     "legendFormat": "interrupts"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(node_exec_context_switches_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}[1m])) by (mode) * 100 / scalar(count(node_cpu_seconds_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",mode=\"user\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "WAN In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"em2\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"em2\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_active_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_buffer_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_cache_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Cache"
    },
    {
     "expr": "node_memory_free_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_inactive_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_laundry_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Laundry"
    }
   ]
  },
  {
   "title": "WAN Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb0\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb0\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb0\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb0\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN Receive Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    {
     "expr": "irate(node_network_receive_packets_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_multicast_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_drop_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_receive_errs_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_swap_in_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_swap_size_bytes{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"} - node_memory_swap_in_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "WAN Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb0\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb0\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb0\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb0\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN Transmit Packets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "irate(node_network_transmit_packets_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "Receive: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_multicast_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "Multicasts: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_drop_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "Drops: {{ device }}"
    },
    {
     "expr": "irate(node_network_transmit_errs_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb1\"}[1m])",
     "legendFormat": "Errors: {{ device }}"
    }
   ]
  },
  {
   "title": "LAN2 In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb2\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"igb2\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  },
  {
   "title": "WIFI In/Out",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"ath0_wlan1\"}[1m])",
     "legendFormat": "In: {{ device }}"
    },
    {
     "expr": "-irate(node_network_transmit_bytes_total{job=\"scrapeConfig/monitoring/opnsense-nodeexporter\",device=\"ath0_wlan1\"}[1m])",
     "legendFormat": "Out: {{ device }}"
    }
   ]
  }
 ]
}